### ISSUE TITLE
No Beatmap Found when giving valid beatmap id

### ISSUE THREAD

**Issue by TheFantasticLoki** [Piggey/osu-sr-calculator#7]
Happens with both beatmap id and beatmapset_id with and without quotations.

**Comment by Piggey** [comment]
I wasnt able to recreate the problem that you have when using `calculateStarRating()` with `map_id` parameter set both as int or string value.

Make sure you use it as 
```python
starRating = calculateStarRating(map_id=1234567)
```

or
```python
starRating = calculateStarRating(map_id="1234567")
```

where `map_id` is BeatmapID and NOT BeatmapSetID

The map obviously has to be already uploaded to osu servers.
